export enum TipoAcaoEnum {
  OV_CRIADA = 'OV_CRIADA',
  OV_STATUS_ALTERADO = 'OV_STATUS_ALTERADO',
  OV_TRANSPORTE_ALTERADO = 'OV_TRANSPORTE_ALTERADO',
  AGENDAMENTO_ALTERADO = 'AGENDAMENTO_ALTERADO',
}
